### ISSUE TITLE
Complete end of summer checklist

### ISSUE THREAD

**Issue by ScottCampit** [sriram-lab/egem#28]
To do:
- [ ] clean up the code into manageable snippets (4-5hrs)
 - [ ] Make all code that are not functions into functions. Clean up all inefficient parts of your code. Make your code in standard PEP8 format.
- [x] generalize the code so that it works with any dataset for gene expression, proteomics, whatever (1-2hrs)
 - [ ]  Same as above, but in addition to making it a function, have it so that the script automates several processes, including mapping gene symbols, etc.
- [ ]  vectorize the code (1-2 hrs)
 - [ ] There are tons of instances were you're dynamically updating variables. This is computationally inefficient. Instead, we should use vectorized implementations via numpy and pandas.
 * A useful resource: https://towardsdatascience.com/python-vectorization-5b882eeef658
- [ ] package them into different scripts (1-2hrs)
 - [ ] Categorize them, and make different python scripts. We're gonna make this a library. For examples, look at the sriram-lab/MetOncoFit project. I want it to look like that.
- [ ] improve the docstring documentation (3-4hrs)
 - [ ] All you functions should have well written docstrings, so that if a developer sees your code, they can read the description and get what's going on immediately. Add comments and such in more appropriate places.
- [ ] improve the wiki documentation (> 1hr)
 - [ ] Write the same description for your functions in the GitHub Wiki site. The point of this is to make it clear to users what each function does, how it does it, and the outputs.
- [ ] re-organize the directory structure/files (>1hr)
 - [ ] Files are everywhere. Clean it up.
- [ ] merge your branch to master (>1hr)
 - [ ]  We need to merge the finished product to master
- [ ] Finally, you should write up your results more formally in the manuscript, as if we were going to publish it soon. (1-3 days)
 - [ ] Read Shen et al., 2019 and format your section (Methods, Results, Discussion) as though it was going to be included in the paper.
 - [ ] Image files should be .svg file format, dpi = 300
 - [ ] I'll want to go over at least 3 revisions with you
